version: '3.7'
services:
  postgres:
    image: postgres:15.1-alpine
    #    network_mode: "host"
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
#      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef

